version: 2
updates:
  # Enable version updates for npm (Node.js dependencies)
  - package-ecosystem: "npm"
    directory: "/demo-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "idvoretskyi"
    labels:
      - "dependencies"
      - "javascript"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/demo-app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "idvoretskyi"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "idvoretskyi"
    labels:
      - "dependencies"
      - "github-actions"