apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml  # Local development (tag-based)
# - deployment-production.yaml  # Production (digest-based) - uncomment for production
- service.yaml
- network-policy.yaml

# For production environments, comment out deployment.yaml 
# and uncomment deployment-production.yaml to use image digests