name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/demo-app

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Check if demo-app directory exists
      id: check-demo-app
      run: |
        echo "Current working directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        if [ ! -d "./demo-app" ]; then 
          echo "Directory ./demo-app does not exist, skipping security scan steps"
          echo "demo_app_exists=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "Demo app directory exists"
        echo "Demo app contents:"
        ls -la ./demo-app/
        echo "Checking for package.json and package-lock.json:"
        [ -f "./demo-app/package.json" ] && echo "✅ package.json exists" || echo "❌ package.json missing"
        [ -f "./demo-app/package-lock.json" ] && echo "✅ package-lock.json exists" || echo "❌ package-lock.json missing"
        echo "demo_app_exists=true" >> $GITHUB_OUTPUT
    
    - name: Setup Node.js
      if: steps.check-demo-app.outputs.demo_app_exists == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: demo-app/package-lock.json
    
    - name: Generate package-lock.json if missing
      if: steps.check-demo-app.outputs.demo_app_exists == 'true'
      run: |
        cd demo-app
        if [ ! -f package-lock.json ]; then
          echo "package-lock.json not found, generating..."
          npm install
        fi

    - name: Install dependencies
      if: steps.check-demo-app.outputs.demo_app_exists == 'true'
      run: |
        cd demo-app
        # Try npm ci first, fallback to npm install --force if dependencies are mismatched
        npm ci || {
          echo "npm ci failed, likely due to dependency mismatches. Trying npm install --force..."
          npm install --force
        }
    
    - name: Run npm audit
      if: steps.check-demo-app.outputs.demo_app_exists == 'true'
      run: |
        cd demo-app
        echo "Running npm audit..."
        npm audit --audit-level=high || {
          echo "npm audit found vulnerabilities or failed, but continuing..."
          echo "Exit code: $?"
        }
      continue-on-error: true
    
    - name: Run Trivy vulnerability scanner
      if: steps.check-demo-app.outputs.demo_app_exists == 'true'
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: './demo-app'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
    
    - name: Check Trivy results
      run: |
        if [ "${{ steps.check-demo-app.outputs.demo_app_exists }}" == "true" ]; then
          if [ -f "trivy-results.sarif" ]; then
            echo "Trivy scan completed successfully"
            echo "SARIF file size: $(wc -c < trivy-results.sarif) bytes"
            # Validate SARIF file is not empty and contains valid JSON
            if [ -s "trivy-results.sarif" ]; then
              echo "SARIF file contains data"
            else
              echo "SARIF file is empty, creating minimal valid SARIF"
              echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"trivy","version":"0.0.0"}},"results":[]}]}' > trivy-results.sarif
            fi
          else
            echo "Trivy scan did not generate results, creating empty SARIF file"
            echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"trivy","version":"0.0.0"}},"results":[]}]}' > trivy-results.sarif
          fi
        else
          echo "Demo app directory not found, creating empty SARIF file for security scan step"
          echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"trivy","version":"0.0.0"}},"results":[]}]}' > trivy-results.sarif
        fi
    
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  build:
    needs: security-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./demo-app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Run Trivy vulnerability scanner on Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        format: 'sarif'
        output: 'docker-trivy-results.sarif'
      continue-on-error: true

    - name: Check Docker Trivy results
      run: |
        if [ -f "docker-trivy-results.sarif" ]; then
          echo "Docker Trivy scan completed successfully"
          echo "SARIF file size: $(wc -c < docker-trivy-results.sarif) bytes"
        else
          echo "Docker Trivy scan did not generate results, creating empty SARIF file"
          echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"trivy","version":"0.0.0"}},"results":[]}]}' > docker-trivy-results.sarif
        fi

    - name: Upload Docker Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'docker-trivy-results.sarif'

  update-manifests:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      packages: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Update image with digest in deployment
      run: |
        # Get the image digest from the built and pushed image
        IMAGE_DIGEST=$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${{ github.sha }} --format='{{index .RepoDigests 0}}' 2>/dev/null)
        
        if [ -z "$IMAGE_DIGEST" ]; then
          # If no repo digest available, use the image ID as digest
          IMAGE_ID=$(docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${{ github.sha }} --format='{{.Id}}' | cut -d: -f2)
          IMAGE_DIGEST="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@sha256:${IMAGE_ID}"
        fi
        
        echo "Updating deployment with image digest: ${IMAGE_DIGEST}"
        
        # Update deployment with image digest
        sed -i "s|image: gitops-demo-app@sha256:.*|image: ${IMAGE_DIGEST}|g" apps/demo-app/deployment.yaml
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local url."https://github.com/".insteadOf "git@github.com:"
        git config --local url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        
        git add apps/demo-app/deployment.yaml
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git commit -m "Update demo-app image to main-${{ github.sha }}"
        git push origin HEAD:main